=== funemy/binary-study/cgc-release-documentation/replay.dtd
<!ELEMENT pov (cbid, seed?, replay)>
<!ELEMENT cbid (#PCDATA)>
<!ELEMENT seed (#PCDATA)>  <!-- 96 hex digits -->

<!-- 
   replay specifies the sequence of actions to carry out
-->
<!ELEMENT replay (decl | write | read | delay)+>

<!ELEMENT decl (var,value)>
<!ELEMENT value (data | var | substr)+>
<!ELEMENT substr (var, begin?, end?)>  <!-- missing begin implies 0, missing end implies len(var) -->
<!ELEMENT begin (#PCDATA)>
<!ELEMENT end (#PCDATA)>

<!ELEMENT length (#PCDATA)>

<!-- timeout values are in milliseconds -->
<!ELEMENT timeout (#PCDATA)>

<!--
  allow 1 or more data elements in write to make it 
  easier for humans to hand craft mixed ascii/hex data blocks
  all data elements are concatenated and written in a single 
  operation
-->
<!ELEMENT write (data | var)+>

<!ELEMENT read ((length | delim),match?,assign?,timeout?)>
<!ELEMENT delay (#PCDATA)>
<!-- match could be a regex for example -->
<!ELEMENT match (data | var | pcre)+>
<!ELEMENT delim (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT assign (var,(slice | pcre))>
<!ELEMENT var (#PCDATA)>
<!ELEMENT pcre (#PCDATA)>

<!ELEMENT slice EMPTY>
<!ATTLIST slice begin CDATA "0">
<!ATTLIST slice end CDATA #IMPLIED>

<!--
   The echo attribute is intended as a debugging feature. When
   echo="yes", the replay utility should echo any data returned
   from a read operation to the local (replay) console
-->
<!ATTLIST read echo (yes|no|ascii) "no">
<!ATTLIST write echo (yes|no|ascii) "no">

<!ATTLIST delim format (asciic|hex) "asciic">
<!ATTLIST value format (asciic|hex) "asciic">
<!ATTLIST data format (asciic|hex) "asciic">
<!ATTLIST match invert (false|true) "false">
<!ATTLIST pcre group CDATA "0">

<!-- make whitspace matter in some elements -->
<!ATTLIST data xml:space (preserve) #FIXED "preserve">
<!ATTLIST delim xml:space (preserve) #FIXED "preserve">
<!ATTLIST pcre xml:space (preserve) #FIXED "preserve">

=== funemy/binary-study/cqe-challenges/NRFIN_00026/pov/POV_00037.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE pov SYSTEM "/usr/share/cgc-docs/replay.dtd">
<pov>
<cbid>service</cbid>
<replay>
    <write><data>\x04\x04\x00\x00</data></write>
    <write><data>\x01\x00\x00\x00\x00\x00\x00\x00\xf0\x03\x00\x00\xe8\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe8\x03\x00\x00\xf3\xef\x04\x0a\xcfl\xf28\x97\x05\x26?\x7c\x197\xe1\x9b\x11q\xfe\xda\x00\x00\x00\x40\x1d\xd99\x93J\xaa\xe4pq\x01\x3e\xe7\x94\x83\xd3\xb4L5\xc2g\xe3uf\xc2\x7d\xf2\x96\xa5\xd8\x14 \x83\xf9J\xfcgCA\x0c\xc5n\xb6\x0e\xa8\xf0:\x8a8\x05\xe4\xd7\xcdF\xa6kl\x19s\x5e\x16\xb6\xc2k\xfbn5\xb6\xe9\x1d\xe8\x60b\xed\xcf\x7d5\x9eS\xcf\xce\x40\x0c\x03uH\x91\xad\xad\x87M\xc28z\xc4\x3ce\x96\xf2\x05\x97:\x17\x1bd\xd3\xbe\x07\x83\x10\xf4\xcd\xddN\x95C\xfa\xe3\x8c\xfd\xd7\xa8DV\x0a\x1a\xdcM\x60\xd9x\xe7\x7c\xbf\xa5\x13\xf4\x3d \xc4\xf0\x84\x5e\x1a\xec\xa4\x91TD\x60\x40\xb9\xb7\xc4\xae\x2c\x0eO\x7bnN\x8et\xea\x12\x8b\x8c\x7c\x8b\x09\xb5\xed\xdd\xb3\x96\x04\x80h\x18xa\xa2\xffA\x91\xed8\x8e\x8e\xb2\x3dT\x25b\xd4\xa9\x5c\x9f\x85f\xa1\xee\xdf1\xe8\xee\x5d\xcfdw\x1dL\xc0\xe9TQ\xa1k\x5d\xa4\x08\xfb\xc3\x9b\x7b\xbd2\xbb\xc9\xfc\x97D\xe6a\xd2U\xe6\xc6D.\x3c\xfc\xeb2\x8c\x18\x05\xf5\x2f\x8b\x04C9W\x02\xf7\x3b\x92\x05d\xdcVG\xbcm\x8b\x14\x88\x08nmo\xb2\x07GIE\xb9\x5fu\x02\x5f\x96\xfeV\xcf\xd4B\xd7n\x08\xb5\x8dK\x1d\x2aK\x15\x7bQ\xd1\xb3\xa8\x81\x15\xd2\xb7PP\x28\x9f\xd1\xc0\x1a\x0a\xcc\x5fm\xec\x5dE\x11\x058e\x9d\xca\x8d\x84j\x03\xd1\xff\x10\x5f\xf4\xac\xa4\xc9\xa5\x08\x00B\x7f\xeb\xd8\x90\x25\x23\x07\x93\x9d\x84\xf9\x87\xbf\x08\x00W\xb1\x94\xea\x7c\x97\xcd\xb9\x95P w\xa7\x15\x24\xbf\xd8\x27D\xec\xc4\x819\xa1L\xfar\xbam\xbc\xba\xe8H\x2f\xcd\x8c\xd2\xd5\x5b\x15\x90\xc5K\x83\xd6\xa7\xe37\xa5\xf9\x01\x27\xdc\x83\xd2\x83\xc1\x91\xcejX\x1a\x2bW\xfa\xd8j\x40\xee\xbe\xb8\x8bc\x86\xf0\xfd\x7c9\x26\x29e\xfa\x25Z\xdfEQO\xb1\xf9\xad\xe5q1\x99\x0cm\x3c\xc0\x9d\xba\x16\xb8\x0a\x09\xd5yPo\xaa\xfb\xaa\xeaI8\xa2\xdaL\x27\x10\xe3\xf07\x86m\xf8\x988\x15\xbb\x90\xb9\xb8\xb8\xeb\xb2k\xdf\x0fiBTz\xea\xfeW\x2b\x2d\x829\x04\xd6\x5b\x7e\xe8a\x99\xb21\xed\xda\xd7\xd3 I\x11\xd7IAu\x95\x91\xe4\x26\x16\x07\xd88\x92g\xd0k\x8e\x1cV\x0a\xaf\x81\x07\xdc\x85\x07\xcd\x5e\xf0\x40\xd7\x10\xb1\x0e94\x99\xd1AN\xf8r\xa2\x19\xc8\xcf\xc6\x291\xc3NV\xc3D\xbd\xcb\xac\xcb\xdd\x837\xec\xe1\x87\xe7\xe3\x1aOT\xa1Q\xfc\xf6\xce\x27\xc3\xbdW\xf9\xe6\x01tx\xeb\xc7P\xa6\x10\xcb\x05v\x07\x09\x09RJ\x08\x26\xf7\xb8n\xb5\xef\x18\xaen\xae\x9a\xb4nO\x99\xfc\x1a\x1b\x92\xa2\x2c\x98\xa8\x60\xf0\xbb\xb8\xb6\x26Le\xad\xf0\xc6\x11\x087\x7f\xb8b0\xe4gs\xd3\x3d\xebs\x05z\x01\xb6\x89\x8b\xafkp\x5b\x19\xd7\xef\xe2K\x3b\xf0e6\xb2\xb5\x261\x5b\x10\x05i\xe4\xb2\x91\x0e\xc6\x92\xa5\xd2\xd4\x7f\x07\xa9\x9d\x16\xeaU\xadL\x8eG\x19\x1d \x7c\xa4\xa3\xa2\xf37\xbe\xd7\xe3\xc8\xb3\x85\x94\x1c6\xa0vaao\x1dc\x11wy\x16\xec\xab\x5fT\xcby\xe1\x01k\x01e\xc0ii3?\xef\xeb\xa4qO\xe1K\x82\x2a0gwR\xcf\x89\xfcf\x5d\xbfD\x96\xf0\x24\x09:\xc3\xdbI\xf1j\x3e\x83\x5c\xc7\xa1D\x1fb\xd3\x08\x3dq\x18\x1e\x1dh\xf1\x05\x11\x11mo\x10\x1f\xc0\xf4\xb52\x96\x9c\xff\x14\xb7\xb20\x10\x0e\x05\x2c!6\xa7\x16\xbb\xeb\xbf\x9f\x3cj\x84A\x3e\xdb\xdb\xd2\xe9\x1c\x2bV\x03\x96\x5c\x5e\xdc                                                                                                                         </data></write>
    <read><delim>\x0a</delim><match><data>Starting dissection...</data></match></read>
    <read><delim>\x3d\x3d\x3d\x3d\x0a</delim><match><pcre>.*New Packet</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===rofl</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===dyewoodsocii</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===iconismanisostemonous</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*Dissection finished</pcre></match></read>
</replay>
</pov>

=== funemy/binary-study/cqe-challenges/NRFIN_00026/pov/POV_00098.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE pov SYSTEM "/usr/share/cgc-docs/replay.dtd">
<pov>
<cbid>service</cbid>
<replay>
    <write><data>\x04\x04\x00\x00</data></write>
    <write><data>\x01\x00\x00\x00\x01\x00\x00\x00\xf0\x03\x00\x00\xe8\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe8\x03\x00\x00\x29\x8c\xcd\x8f\xc7\xa4\x14I\xee\x24W\x11\x2f\x00\x00\x00P\x98\x80\xd2D\x23!\x06\x3b\xbe\xb9\x89\x00\xdd\xfebI\x1a\x18T\x8d\x9f\xcfF\x7crD\x5e\x00q\xd7\xfc\x5c\xb0vjc\xf5\xf8F\x11\x16b\x2f\x8f\x0c3\x00\x02\xce\x03\xe1\xa2\xd8\x033\xac\xae\x9d\x29\x7f\x0d\xd2\x9f\xfe\x2f\x18\xc0I\x07\xe7\xf5\xf4\x1a\x90\xc4b\xcaF\xf2\xfe\xda\xbcU\xa22\x87\xb3\x1c\xf7\xea3\x40\x2c\x3e\x93\xd8\x9b\xb8Y\x8c\x2dg\x7b\x5fv:\x08\x8d\xc3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </data></write>
    <read><delim>\x0a</delim><match><data>Starting dissection...</data></match></read>
    <read><delim>\x3d\x3d\x3d\x3d\x0a</delim><match><pcre>.*New Packet</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===lol</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===kempstergarefowl</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*Dissection finished</pcre></match></read>
</replay>
</pov>

=== funemy/binary-study/cqe-challenges/CROMU_00039/pov/POV_00000.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE pov SYSTEM "/usr/share/cgc-docs/replay.dtd">
<pov>
<cbid>CROMU_00039</cbid>
<replay>
    <write><data>\x00\x93\x01\x25\x90aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</data></write>
    <read><length>5</length><match><data>\x00\x03\x04\x25\x01</data></match></read>
</replay>
</pov>

=== funemy/binary-study/cqe-challenges/NRFIN_00026/pov/POV_00119.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE pov SYSTEM "/usr/share/cgc-docs/replay.dtd">
<pov>
<cbid>service</cbid>
<replay>
    <write><data>\x04\x04\x00\x00</data></write>
    <write><data>\x01\x00\x00\x00\x01\x00\x00\x00\xf0\x03\x00\x00\xe8\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe8\x03\x00\x00\xdd\xda\xfd\x11\xba5XNK\x80\x27C\x98\x00\x00\x00\x60s\x0b\x11\x0a\x83\x40\xba\xd8\xfc\xd1\xea\x3cs\xcfV\xdbm\xccr\xdd\x15\x0a\xda\x3cN\xb0pF\xf7\x92\x93UW\x13EM5\xe7\xa3\xbd\xd4E\x82\xd8\xa2\xba\xebd\xc1\xef\x2f\x8daV\x3b\x3dX\x00\x5b\xb4\xcc\x2az\xfa\xe3\xdc\xc3\x22\xcd\x88\x02N\xc3\x9b\xac\x0e\x1d\xeb\x82\x87\xf1\xa2\xeaB\xb6\x86\xee\xa1\xf3\xbay\xde\xeb\x1aj\xa1\x16\xb7\x5f\x00e\xd1\xebr\xbf\xd4\xc5\x18Kn\x82\x15\x87\xd0\xa1\x11\xc6r\x9a\xde6\xb8\x7c\x5f\xf2\x3b\xf3b\x0a\xb3\x95\x2d\xab\xa1\xaf\x9e\xce\x25\x5f\x00\xd4o\xac\xf6l\x13Z\xd4\x27\xa0R\xabX\x9e\x83\x92\xda\x3bZOI\xa5Z\xb7\x7d\xcfh\x22\x13\x9c\x98Y\xcd\x93\x9a2Um\x89v\xf0\xf5\x12i!\x97\xab\xe8\x8a\xa4J\xb0S\x80b\xd8\xacB\x5f\xb8L\xb0\x17Qgs\xce\xd0E\x99\xbb\xb0\x10\x04\x9d\xdfU\x15\xac\x9e\x5b\x24\x7d\xfcrZK\xeeF\xe0\x17\xe4\xa5\xfd\x5d\x27\xac58\x60\xdc6\x3e:\xd6w\xb6\x0a\x83\xa0\x25\xa5\xf4\x7e\xef6L\x22\xfe\x1d\x28\xd4Z\xe0\xc2a\x80e\xe4:\x7f\xfeK\x7d\xc8\x2bb\xd8\x3dD\xa1\xb4\x7e\x11\xf7H\x3bi\x85\x27Q\xc1\x3d\xfc\xbf\x06\xcb\x0e\xca\x26\xb6NcB\xc9 \x12\xfb\xfc\xbe\x3c\x94\xd1\x9a\xe6\xda\x121\xc2\xd6:\xae\x9c\xed\x1ai5\xa0\x83I\x14\x1cI\x90x\xb2\x92Z\x1b\xd0\xdc\x97\xac\xd7?\xd2\xdf\x24?T\x22\x93e\x5f\xd9\xb0a\xd1\xd1\x5f\x00b\x19\xa6\x29\x1e\x25T\xe53\x5f\xa8\x05\x11\xe1\xb0\x9f:\xac\x88\x24\x3br\x2fG\xcc\xadIS\x9b\xec\xc2\x8a\x822\x40\xe0\x3b\xb89\x5fQ\xeb\xa3\x84Ld\xd8\x7d\x29\x7c\x7d\xe0\x92\x2ds \x00\x5d\xe4\xdd\x2dh\x8d\x83\xb1q\x89\xb0\xbe!?M\x0e\x0d\x12\x27Jaa\x0c\xf71\x13\xdf\xbf\x0c\xcb\x09\xbd\xa8j\x22\x94\xb4\xdd\xf99\x5f\x7c\x2f\x17\x14\x3dA\x92\xb9\xcb\x01\xb3\xff\x3e\xab1\xda\x7f\xd4H\xaf\xe3\xca\x25\x2c\x9e\xe0\xbe\xcdRT\xe7d\xd2\x16\xebX\x0f\x0d\x1c\x80\xab\x7f\x9d\xc9\x04\x93\x15\xa2\xfc\x0aW\x2d?\x957j\xf4\xe3u\xb6\xb2c\x13\xfe6\x18\xfd\x0fm\xe2\xa2\x8a\xf5\xa7\xab\xa6\xa2\x0b\xcafL\xdd\xb2\x1dH\x00O\xd6\xb5\xac\x7dz\xc2\x5f\xf0\x7b\x25M\x26\x40V\x80f\xde\xb7l\x9d\x98\xb7d\x98:\x2c\xaa\xec\xfe\xfa\x06\xd9q\xacc\x02W \x02\xe9\xa5Z\x14\xd9\xf22x\x2a\xb24\x1f\xb1J\x0f\xb2\x2dL\x93\xf1\x97G\xec\x82\xaf\xc6\x98\x87\x7fj\x2f\x98\x14\x08\xdb\x05\xe85\xcfB\xab\x15l\x10\x0aS\xd0\x19\x1d\x10\xcc\xfev\xa0\x01\x89\x01N\x08\x0a\x9e\xf1\xe6.E\xc1\xa0Wo\xc1\xe2\x92\xfc\x89\x0f\xfb\x1b\xf5\xcbG\xf4\x00n\x03\x9d\xf5\x10\x93\x95\x9dc\x82C\xed6k\xc0\x40k\xfb\x044\x0d\xce\xd7\xe5\xd2L\xb8\x3e\xff\x12\xb0\x18\x2d\xa3\x22\x83\x2c\x29\xa8\x9b\x03a\xfb\xeb\xeb\x0d!\x7b\xa2\xb1\x17\xbax\xa6\xcer\x95\xca\xbb\x83\x05\xaf\xe8\x04\xe8\x08\x19\xa0\xa1\x2fW\xce\xf3\x143\x89\xfbS\x0a!\x89\xc9\xc9\x18\x28\x05\xb0\xf5\x408\xba\xfd\x99\xde\xe0\xf8\xa0d\x5eR\xca\xd0\xe5\x99\xf4\x91B\x0ei\xb2\xee\xc0\xa3p\x86\x3cbx\x15\x1e\xbc7\x91\xd7\x08\xd9\xb1\x5f\x5b8\x0c\x08\x19\x2f\x1a?\xa3ab\xc5\xda\xa8UTh0\x5fU\xa0Y\x05\x8d\x93\xf2\x223\x94\x27\xcc\x99\xae\xc7\x83\xb2\x9d\xd1\xdf\xd0:\xc4N7Y\xe1\xc0\xf0?\xd0\xbe\xdf\x25\xb3\x04\x5f\xce\x07\xb4\xb9\xc9\xe8\x88\x253\x40\x2b\x81ig\x60\xe3\x8d\x1d\xcc\x9a\xceB\xd0\x86ugKE\x87:\xb0\x85v\x1a9\x226\xeef\xef\xd11\xc0f                                                                                        </data></write>
    <read><delim>\x0a</delim><match><data>Starting dissection...</data></match></read>
    <read><delim>\x3d\x3d\x3d\x3d\x0a</delim><match><pcre>.*New Packet</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===lol</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===assentaneoushemal</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*Dissection finished</pcre></match></read>
</replay>
</pov>

=== funemy/binary-study/cqe-challenges/CROMU_00021/pov/POV_00003.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE pov SYSTEM "/usr/share/cgc-docs/replay.dtd">
<pov>
<cbid>service</cbid>
<replay>
    <read><length>2</length></read>
    <write><data>"A" * 4294967295\n</data></write>
    <read><length>2</length></read>
    <write><data>terminate\n</data></write>
</replay>
</pov>

=== funemy/binary-study/cqe-challenges/NRFIN_00032/pov/POV_00008.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE pov SYSTEM "/usr/share/cgc-docs/replay.dtd">
<pov>
<cbid>service</cbid>
<replay>
    <write><data>e\x01\x00\x00</data></write>
    <write><data>\x01\x00\x00\x00\x00\x00\x00\x00M\x01\x00\x00E\x01\x00\x00\x00\x00\x00\x00\x10\x01\x10\x10\x00\x00\x00\x00E\x01\x00\x00\x5ew\x86\x2d\x1bl\xbe!\x0e\xad\x7bu\xb7\xea\xe3dv\x89\xdcEW\x00\x00\x00\x01\x005:\x89\x5e\xbd\xcb\xb3I\xf7\x01\x16\x29\xdff\xd9\x2d\x86\x232vv\xa0\x01\x01\xa5A\x00RK\x05\x87b\x40s\x9e\xffW\xeaV\x9f\x129o\x91\x06\xd1\xceh\x5d\x81G\xfe6\x9616v!\x0cCCy\xd9\xef\xd9\x06\xb3\xeb\xc85\xa3\xb7\x02\x0f\xd0\xb8\xb3\x2a\xeb\x9e\xb5\x2f\x0981\xb3\xd9\xceK\xa9\x25\xd7\xb7\x04 \xb4\xe6\xabq\xd9\xc7\x822o\xb1\x08\xban MGd\xc1\x8e\x8d\x10\xa8\x9b\x8e\xe3\x0e\x02n\xf3\x85l\xbc\xbe\xce\x07\xc7S\xabJ\xc0L\xaa\xc4\xad\xc2\xea\x03ow\xe1\xfdK\x910\xf4\x97fy\x08\xdcH\xe9\xc4\xcbZh\x10\xd2\xe2\x2b\xdc\xa8\xd8\xb6\x9f\xb1R\x96\x40\x08tA\xbf\x96\xa1\x0dg\xe1N\x80\x18vt\xf5T\x10\x9b\x9f0\x99:\xd2o\xfd\xb2HZ1\xde\xc7\x07\x00\xd2\xcb\xb2\x7b\x8er4\xf8\xad\x7bq\x2b\x0d\xe5\xf2\x99\xe5\xfa\xca\x067\x5b\xfe\xb8V\xe9a\x1c\x80\xf2\x22\x0a\xf4\x29\xda\xb0\xcc\x9c\xf1T:\x80\x9c\xf1\xd0\xe1\x04\xd8\xc8\xb6\x00\xe6or\x5d\xf3\x28\xae\xe06\x0d\xe02\xa7:H\xcbq\x04\xf4p\x40\x23\x93\x91\xb7\x7b\xe3\xf4\xb4\xe2\x7f\x03\xbdA\x00x\x3dA\x00\x01\x96</data></write>
    <read><delim>\x0a</delim><match><data>Starting dissection...</data></match></read>
    <read><delim>\x3d\x3d\x3d\x3d\x0a</delim><match><pcre>.*New Packet</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===llama</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===llamacoruscant</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*Dissection finished</pcre></match></read>
</replay>
</pov>

=== funemy/binary-study/cqe-challenges/KPRCA_00013/pov/POV_00001.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE pov SYSTEM "/usr/share/cgc-docs/replay.dtd">
<pov>
<cbid>service</cbid>
<replay>
    <write><data>S84\x3d\x22LFVyep4KvgZ4qbmBLmJEtw1du1wgGvfl941JObTvwHqEQL5YYY90dR68FuJia21rTqbJz4QRZ80RH5sAoM8ffEXXPLQD7DDBKrEZ\x22\x0aA94\x3d\x2d78585.593\x0aCLEAR E13\x0aO23\x3d\x3d\x28LN\x28Y41\x29 \x2b 59571.468\x29\x0aSHOW W42\x0aH61\x3d\x3dCOS\x2885496.765\x29\x0aCLEAR F53\x0aREPR Z3\x0aO96\x3d\x2d26342.878\x0aCLEAR X66\x0aREPR F K7\x0aU6\xfe\x3d\x2204QtH4A2eQ2cT4bBZTLSCluH0mmJazDXy5rUP7C0CimFtR7gVT7VA7d2NSwvFcEDfvdiMrBIAMwnr3NZrBiZiYM9GPyGN4ldJykx\x22\x0aREPR B38\x0aP7Q\x3dLN\x28\x28SQRT\x28S59\x29 \x2b 85590.734\x29\x29\x0aCLEAR R28\x0aCLEAR L65\x0aREPR R94\x0aQ40\x3d2991.271\x0aCLEAR J0\x0aSHOW K1\x28\x0aE4\x28\x3d19090.558\x0aV17\x3d\x2d78374.418\x0aREPR G13\x0aX17\x3d\x2d97874.298\x0aSHOW T39\x0aO14\x3d88859.596\x0aCLEAR Z50\x0aSHOW V55\x0aC\x3bEAR P94\x0aR75\x3d\x2d1559.905\x0aCLEAR R76\x0aCLEAR J71\x0aCLEAR S44\x0aCLEAR Q82\x0aV72\x3d\x3d\x28\x2d30440.695 \x2f MAX\x28LN\x28\x2833098.600 \x2d 43702.098\x29\x29\x2c \x2d47880.669\x29\x29\x0aSHOW H16\x0aI32\x3d65263.192\x0aSHOW Y56\x0aZ79\x3d\x22ctpvPW0j9TPnWBeYdShv7HkS7pZKJ7uhmC1WtFfAaa12ksKIm3bKLkxCjHFnT1cBxWGJCrlvhHtLoDIS6yJsFrzueYEMycUxv6o0\x22\x0aREPR E36\x0aT46\x3d\x3dSQRT\x28W26\x29MEDIAN\x0aCLEAR V1P\x0aCLEAR O86\x0aCLEAR D95\x0aREPR M32\x0aD47\x3d\x3dPOWER\x2840507.433\x2c CO9\x28\x2d73964.156\x29\x29\x0aW71\x3d\x2d64577.432\x0aSHOW B43\x0eCLEAR O44\x0aSHOW U68\x0aSHOW O14\x0aSHOW W71\x0aSHOW P7\x0a O96\x0aSHOW O23\x0aSHOW V72\x0aSHOW V17\x0aSHOW Z79\x0aSHOW 2\x254\x0aSHOW R75\x0aSHOW I32\x0aSHOW H61\x0aSHOW A94\x0aSHOW X17\x0aSHOW D47\x0aSHOW T46\x0aSHOW E47\x0aEXIT\x0a</data></write>
    <read><length>1</length></read>
    <read><length>1</length></read>
</replay>
</pov>

=== funemy/binary-study/cqe-challenges/NRFIN_00026/pov/POV_00117.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE pov SYSTEM "/usr/share/cgc-docs/replay.dtd">
<pov>
<cbid>service</cbid>
<replay>
    <write><data>\x04\x04\x00\x00</data></write>
    <write><data>\x01\x00\x00\x00\x01\x00\x00\x00\xf0\x03\x00\x00\xe8\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe8\x03\x00\x00\xdbp\xdb\xb0\xcf\x04\x3cp\x85J\xda\x92\x90\x00\x00\x00\xb8\x8b\x7c\xbc\x13\x00\xf7\xff\x1f6K\xefl\xde\x13\x00\xc6r\x9d\x1aI!\x02\xc9\x0b\xe9\x3bC\xb0\x0b\x91\xd5\x5d\xfd\xee\x0dj\xa8\x7d\xd9d\xed\x23\xe5d5A\xf7\xb7\xf1\x84\x12\x9d\xec\xd2D\xbbcF1G\x89kPW\x02\xd4G6\xe3\x13\x60\x96\x18\xcd\x06\x0c\xcbg\xe4\xac\x95\xa5\x27\xd0\xb4\xde\xe6\x3dj\x01o\xb6\xfbk\x9et\x00\xe8\xad\xc6\xcc\x18\xf2\xa1\x8e\xfbk\x87\xa0\xddI\x7e\x8aC\x15\xe5\xd0\x9aM\x8bR\x40\x9f\x93\xcf\xf0\xdf\x29\x5d\x9c\x80\x83\xce\x28t4\xe4YW\x90e\x06w\xefn\x99\xb0\xca\xcd9\x1a\xc4R6\xca\xc5\x19\xea\xb7\xfd\xd9\x3e\xb4\xf1b\xff\x9fO\xe0\xe8\x1an\xed\xb8\xaeP\xa8\xd0\xe6\x1cKu\x0f\x18m\xf86\x0a\x24\x9a8\x0b\xf9j\xf4d\xc4PG\x9f\xe2\x8f\x26\x2fZ\xf4\xfe\xc6m\xf7\x24\xc9\x81\xbc:?b\xe6\xad\xde\x9a\xf3\x80\x11\x9e\x7b\x80S\x2b:\x88\x5bKEO\x0d\xc7\x10\xb8\xc6\x9b\x9f\x27\x87\x7e\x3e\x5e\xab\xbc\x23\x01\x9c\x08\x0f\xc0\x28Hy\x92\x12W\x9aZ3\x5chI\xe5b\x07Cb\x7dF\x8c\xc9\xd8\x7euL\x1fq\xdahx!\x2d\x86\x8d\x92T\x98\x8f\xcc\x1d\x8f\x15\xde\xda\x9d\xe7M\x22\xa3\x5d\xca\xd6\xa1\x0b\x0e\x13\xbb\xc1\xba\xab\xef\xe0\xf8\xdd\xce\x1b\x82\xe9W\xb5\xef\x0f!\xadgr1\xc3\xd9\x1c\xbdw\x29\xf0\x7c\xa9r\x9c\x9e\x16\xa2\x12\xbf\x7d\x995\xb7J\xd1\xfb\xcd\xaf\x16\x07\xded\xe9\x22\xa6\x08\x9d\x60\xb2\xf8\x89d\x11\x29\xa2Z\x27\xd1\x0c\x5c\xf8\x8c\x0fp\x2d.\x7f\x5b\xa9\xf4\x7c\xcbMH3\xf0\x14\xce\xad\x96\xf5\xbe\xf5\xdd\xb8\xa2\x2aVJ\x09\xd1\xad\x07\xecB\x07\xc1a\xba\xfeA\x90\x03\x1f\x3d\xd7\x0d\xdc\x2a\xac\x8fYjkX\xaa\xf8\xa8\xf8nx\xf2\xebr\xae\xd6Vl\xdf\x10\xe2\xb9\x99g\x14\x1aa\xb4\x1fo\x07n\x5b\xcd\xb39\xd8\xe2\x04\x99\xcaZ\x22\xb0\xf6\xe8\x5d\xcdR\xafz\x00\xf9\x2b\x89\xf5\xdc\x88\xef\xc0\xad\xc9eO\xe1\xaf\x2f\x27\xd6\xf4L\x5b\x8c\xd8\x93\xc7\xe6\x9fE\xa8O\xc8!\x13\xfc\x0e\xde\xdf\xb9O\xf2I\xe8H\xb5\x19\xcc\xe8\x1bI\xd8HC\xae\x0dK\x7e\x0d\x90x\xe5\xed\xe5\xbd\x11\x5e\x95\xa0\xcc\xf1\xfa\x93\xae4\xe1\xe1A\xdb\x3e\x82\xc8\x8f\x2a\xbe\x27\xb7\xac\xd7\xbdC                                                                                                                                                                                                                                                                                                                                                                                                                              </data></write>
    <read><delim>\x0a</delim><match><data>Starting dissection...</data></match></read>
    <read><delim>\x3d\x3d\x3d\x3d\x0a</delim><match><pcre>.*New Packet</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===lol</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===undercropArenga</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===menialitypreintelligent</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*Dissection finished</pcre></match></read>
</replay>
</pov>
