=== funemy/binary-study/cgc-release-documentation/replay.dtd
<!ELEMENT pov (cbid, seed?, replay)>
<!ELEMENT cbid (#PCDATA)>
<!ELEMENT seed (#PCDATA)>  <!-- 96 hex digits -->

<!-- 
   replay specifies the sequence of actions to carry out
-->
<!ELEMENT replay (decl | write | read | delay)+>

<!ELEMENT decl (var,value)>
<!ELEMENT value (data | var | substr)+>
<!ELEMENT substr (var, begin?, end?)>  <!-- missing begin implies 0, missing end implies len(var) -->
<!ELEMENT begin (#PCDATA)>
<!ELEMENT end (#PCDATA)>

<!ELEMENT length (#PCDATA)>

<!-- timeout values are in milliseconds -->
<!ELEMENT timeout (#PCDATA)>

<!--
  allow 1 or more data elements in write to make it 
  easier for humans to hand craft mixed ascii/hex data blocks
  all data elements are concatenated and written in a single 
  operation
-->
<!ELEMENT write (data | var)+>

<!ELEMENT read ((length | delim),match?,assign?,timeout?)>
<!ELEMENT delay (#PCDATA)>
<!-- match could be a regex for example -->
<!ELEMENT match (data | var | pcre)+>
<!ELEMENT delim (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT assign (var,(slice | pcre))>
<!ELEMENT var (#PCDATA)>
<!ELEMENT pcre (#PCDATA)>

<!ELEMENT slice EMPTY>
<!ATTLIST slice begin CDATA "0">
<!ATTLIST slice end CDATA #IMPLIED>

<!--
   The echo attribute is intended as a debugging feature. When
   echo="yes", the replay utility should echo any data returned
   from a read operation to the local (replay) console
-->
<!ATTLIST read echo (yes|no|ascii) "no">
<!ATTLIST write echo (yes|no|ascii) "no">

<!ATTLIST delim format (asciic|hex) "asciic">
<!ATTLIST value format (asciic|hex) "asciic">
<!ATTLIST data format (asciic|hex) "asciic">
<!ATTLIST match invert (false|true) "false">
<!ATTLIST pcre group CDATA "0">

<!-- make whitspace matter in some elements -->
<!ATTLIST data xml:space (preserve) #FIXED "preserve">
<!ATTLIST delim xml:space (preserve) #FIXED "preserve">
<!ATTLIST pcre xml:space (preserve) #FIXED "preserve">

=== funemy/binary-study/cqe-challenges/NRFIN_00032/pov/POV_00018.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE pov SYSTEM "/usr/share/cgc-docs/replay.dtd">
<pov>
<cbid>service</cbid>
<replay>
    <write><data>\x83\x01\x00\x00</data></write>
    <write><data>\x01\x00\x00\x00\x00\x00\x00\x00k\x01\x00\x00c\x01\x00\x00\x00\x00\x00\x00\x10\x01\x10\x10\x00\x00\x00\x00c\x01\x00\x00\x0b\xfao\xb0\xdf\x1b\x96\xfd\x8f\xb7\xca\xael\xff\x98\xe0\x2d\xad\xc16\x60\x00\x00\x00A\x00\xed\xb4A\x00\x2fl\x26\xb0\xfd\xcc\xf8\x01\xe0\xad\xb4\x7f\x97\x01f.\xaa\xbb\x8d\x96\x1a\x9bn\x01\x97\x01\x00\xb8A\x00\x01C\xff\x82\xefzU\x8a\x9f\x60\x2a4\xe3\xe8\x87\xc7N\x2d?X\x97\x17\xcf\x93M\x1b\xf9\xf2v\xf0\xfa\xefn\x0a\x08\xf1\x83\x94!1\xc7\xf8\xed\xca\xa1gp\xd2t\xcc\x15\xfa\x8f\xa8\x3eV.\xc93\xf6\x23\x27\xf2\xf8r\xb7\xbeU\x01\xbd\x83o\xe9k\x92\xec\xf0?z\x2bj\xf1\xa1ca\x00\xe7\x2f\x85\x1f\xf5\x83BE8\xb63K\x27\x97X\xe24\xff\x5dB\xb3g\xbaL\x9a\x9b\xad8\xc0\x92\x86\x84K\xe3\xd5\x9bS\xdf\xef\x3e!\x7c\xedBpo\x9aZhq\xf8\x3d\x98\x80\xe1\xe0\xf2\x1e\x01\xaa\x81\xc4I\xf2\xf0t\xebz\x04.\xa1?\xf9\x96W\xd4H6\xef\xe2zq\xa3z\xb8\xf6M\xc3exf?\x2f\xe07\x28tt\x25\x2a\x28\x0er\xa5q9\xb1\xb2\x18\xfc\x3b\xec\x96\x8e\x9aC\xa8cM\xf1\x11m.\x27\x8a\xa1\x17\xa9\x9fu\xced\x89\xc1.\xbco\xf4\xd0\xb7\x81\x9e\x22\xc5T\x13\xb3\xed\xd9\x23\x60\xa1\xc6\xc9\xf7\x13\xba\x0e\x02\x1b\x04\x5d\xeb\x8c\x10\xb3fP\x04\x18\x9b\x28\x01\x00\xa0\x01\x00d\x01\x00\xb1\x01\xa1\x01\x00\xdd\xa4 \xbc\x1c\x3eS\x10\x23\xae\x87\xb4\x9d\x01\x19\x01\x00 \x01\xc4A\x00A\x00</data></write>
    <read><delim>\x0a</delim><match><data>Starting dissection...</data></match></read>
    <read><delim>\x3d\x3d\x3d\x3d\x0a</delim><match><pcre>.*New Packet</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===llama</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===llamaantimaterialistic</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*Dissection finished</pcre></match></read>
</replay>
</pov>

=== funemy/binary-study/cqe-challenges/NRFIN_00026/pov/POV_00006.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE pov SYSTEM "/usr/share/cgc-docs/replay.dtd">
<pov>
<cbid>service</cbid>
<replay>
    <write><data>\x04\x04\x00\x00</data></write>
    <write><data>\x01\x00\x00\x00\x00\x00\x00\x00\xf0\x03\x00\x00\xe8\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe8\x03\x00\x00\xa7l5\xa4\x8f\xfc\xfd\x3bj\xe9\xf8\x9b\x2d\x5b\xec\x95\x08\xff\xfa\x2f\x1a\x00\x00\x00\xcfh\xad\xc3\xf4O\xd4A\x7c\x02\xc9MA\xf3\x9c\xe5\x1e:\x90\xcf\x2d\xfd\xd4\xcb5\x85\xc8\xc5.\xf02\xf5\x3cF\xfc\xf0\x5c\x5c\x14 G\xc8\x0f\xe4H3\x1d\x15ey\x07\x3cc\x82\x01H\xc8\x08\xe9\x91\x1f2\xe4\xbb\x1c\xb0\x02\x85\x8eS\xb8.\x1b\x244\xbe?\xfbL\x00nKo\x8f\x18F\x9b\xe4r7\x0e\xe4\xcc\x10\x88\xc3\xb4PX\x06\x7c\x5d\xe6\xa2\xef\xb2M\xb9\xcf\xfb\xc3\x97\xa5\xcd\x7e\x03\xde\xa7\x96\xc2m\xef\xd6Z\x08\x17\xb7\xd5Y\x2c\x8d\x0a\xc1\x00?\xbc\xf4\xb7?\xb4T\xdd\x17m\x9e\xdb\xc0\xa4\x80\xaf\xc1\x87\xbda\xe8\x86\x2f\x5b\x18\xbdF\xa5\xaf\x10\xb6\xc8\xdc\xef\x08Om\xabL\xd1\x22\x7f\x06\xfa\x83\xc2Q\xcf\x29\x1d\xaa\x8e3r\x27\xc7\xb7T\x91\xe7F\xe2K\xd9\xbd\xaf\xacS\x04w\x01\x8a\xc5\xeeg \x00\xa16U:Y\xbd\xbbN \x00 \x00\x0d\x90\xb85F\xe6fd\xb4E\xcd\xbbV\xaaD\xf8\x08\x10\xa2\xd0\x88\x04i\xa6\x0f\xac\x7b\xef\x8eQ\xbbk\x956\x27\x19p\x8a\x5c\x3ew\x93\x80G\xbc\xa6\xf0S\x0b\xf1vq\xec\x9d\x93\xacD\xeb3\x8bi6\x0c1b\xe6W\xb5\x18\x1d\xf9\x16vL\x5e\xe8\x92\x0c\xec\xf0\x3d\xfc\xb8W\xa1\xb7\xfa\xaa\xf7\xa91\xee\xa2\x1f\x04\xc2\x1bM\x22\xe0\xba\x8e\xbe\xe2\xbdJ\xed\x8a\x02\xf6PB\x94\x8b\xde\xc1\x8d\x97\xe5\x00\x2fRC\xc7\x8d\x90j\x856\x8e\x60\x3d\x09\x97 \x0f\x7d\x0d\x14\x26\x84\xdd\xb1 v\xbf\x09\x2a\x3d\xd8KZ\x14\xe5\x81\x25\x07i\x0a\x89X\xcb\x0d\xf6\xb5k\x8d\x85\xe0\x40\xc8\x00D\xb5\x1c\xaa\xdc\xa8a\x10w\x8d\xf0\xa0\x5fb\xf4\xfc\xe6\xd9\x0e\xd5dl\xa3u\x9d2\xb6\xc2\xca\xc6\x8f\xc7\xa9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </data></write>
    <read><delim>\x0a</delim><match><data>Starting dissection...</data></match></read>
    <read><delim>\x3d\x3d\x3d\x3d\x0a</delim><match><pcre>.*New Packet</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===rofl</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===receptivenesssempervirent</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*Dissection finished</pcre></match></read>
</replay>
</pov>

=== funemy/binary-study/cqe-challenges/KPRCA_00046/pov/POV_00001.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE pov SYSTEM "/usr/share/cgc-docs/replay.dtd">
<pov>
<cbid>service</cbid>
<replay>
<write><data>new\x0a</data></write>
<write><data>sd 1\x0a</data></write>
<write><data>q2q4\x0a</data></write>
<read><delim>\x0a</delim><match><data>move p7p5\x0a</data></match></read>
<write><data>p1r3\x0a</data></write>
<read><delim>\x0a</delim><match><data>move s8r6\x0a</data></match></read>
<write><data>n1o3\x0a</data></write>
<read><delim>\x0a</delim><match><data>move p5q4\x0a</data></match></read>
<write><data>o3q4\x0a</data></write>
<read><delim>\x0a</delim><match><data>move p8p4\x0a</data></match></read>
<write><data>r1n5\x0a</data></write>
<read><delim>\x0a</delim><match><data>move o7o6\x0a</data></match></read>
<write><data>n5p3\x0a</data></write>
<read><delim>\x0a</delim><match><data>move o8s4\x0a</data></match></read>
<write><data>r3r4\x0a</data></write>
<read><delim>\x0a</delim><match><data>move r6q4\x0a</data></match></read>
<write><data>r4q4\x0a</data></write>
<read><delim>\x0a</delim><match><data>move q7q5\x0a</data></match></read>
<write><data>s1r3\x0a</data></write>
<read><delim>\x0a</delim><match><data>move p4q4\x0a</data></match></read>
<write><data>p3q4\x0a</data></write>
<read><delim>\x0a</delim><match><data>move s4r3\x0a</data></match></read>
<write><data>s2r3\x0a</data></write>
<read><delim>\x0a</delim><match><data>move r8n4\x0a</data></match></read>
<write><data>o2o3\x0a</data></write>
<read><delim>\x0a</delim><match><data>move n4p6\x0a</data></match></read>
<write><data>p2p4\x0a</data></write>
<read><delim>\x0a</delim><match><data>move q5p4\x0a</data></match></read>
<write><data>o3p4\x0a</data></write>
<read><delim>\x0a</delim><match><data>move t7t5\x0a</data></match></read>
<write><data>o1s5\x0a</data></write>
<read><delim>\x0a</delim><match><data>move n7n5\x0a</data></match></read>
<write><data>t2t4\x0a</data></write>
<read><delim>\x0a</delim><match><data>move r7r6\x0a</data></match></read>
<write><data>s5p2\x0a</data></write>
<read><delim>\x0a</delim><match><data>move q8r7\x0a</data></match></read>
<write><data>m2m4\x0a</data></write>
<read><delim>\x0a</delim><match><data>move n5n4\x0a</data></match></read>
<write><data>m1o1\x0a</data></write>
<read><delim>\x0a</delim><match><data>move t8q8\x0a</data></match></read>
<write><data>q1r1\x0a</data></write>
<read><delim>\x0a</delim><match><data>move q8o8\x0a</data></match></read>
<write><data>p4p5\x0a</data></write>
<read><delim>\x0a</delim><match><data>move p6q5\x0a</data></match></read>
<write><data>p5o6\x0a</data></write>
<read><delim>\x0a</delim><match><data>move q5n2\x0a</data></match></read>
<write><data>o1o5\x0a</data></write>
<read><delim>\x0a</delim><match><data>move n4n3\x0a</data></match></read>
<write><data>o6o7\x0a</data></write>
<read><delim>\x0a</delim><match><data>move n8m6\x0a</data></match></read>
<write><data>o5m5\x0a</data></write>
<read><delim>\x0a</delim><match><data>move m6o7\x0a</data></match></read>
<write><data>q4m8\x0a</data></write>
<read><delim>\x0a</delim><match><data>move o8m8\x0a</data></match></read>
<write><data>m5t5\x0a</data></write>
<read><delim>\x0a</delim><match><data>move n2q5\x0a</data></match></read>
<write><data>r1q2\x0a</data></write>
<read><delim>\x0a</delim><match><data>move r7s6\x0a</data></match></read>
<write><data>t5q5\x0a</data></write>
<read><delim>\x0a</delim><match><data>move r6q5\x0a</data></match></read>
<write><data>t1o1\x0a</data></write>
<write><data>quit\x0a</data></write>
<read><delim>y</delim></read>
<read><delim>\x0a</delim><match><data>e\x0a</data></match></read>
</replay>
</pov>

=== funemy/binary-study/cqe-challenges/CROMU_00034/pov/POV_00003.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE pov SYSTEM "/usr/share/cgc-docs/replay.dtd">
<pov>
<cbid>service</cbid>
<replay>
    <read><delim>\x0a</delim><match><data>Welcome to the diary logger!</data></match></read>
    <write><data>\x04\x01</data></write>
    <write><data>BBrp\x08\x00\x00\x00\x02\x03\x0e\x00C\x00\x00\x03\x11\x15\x00\x26\x00cbababcbacbcbaaca\x01\x03\x0f\x2d\x00\x3c\x00baccccbcbbabaaa\x05\x00\x00z\x00\x00\x00\x03\x04I\x00\x97\x00\x00\x03\x0aP\x00Z\x00bcbcaaaaaa\x05\x04\x00\x01\x00a\x00\x02\x03\x10h\x00x\x00abaacabbababaacc\x03\x03\x18\x7f\x00\x00\x00cccaaabbaccabbabaccaaacb\x01\x03\x9d\x00\xcd\x00\x00\x03\x0e\xa4\x00\xb2\x00accaacbaacbcca\x05\x03\x0d\xb9\x00\xc6\x00abbcaaaccbaac\x04\x01\x00\xfa\x93\x00\x00\x02\x04\xd3\x00\x00\x00\x09\x03\x12\xda\x00\xec\x00abccabccacacacbbab\x01\x03\x03\xf3\x00\xf6\x00abb\x05\x00\x00K\x00\xfd\x00\x03\x01\x00\xe1y\x00\x00</data></write>
    <read><delim>\x0a</delim><match><data>Length: 260</data></match></read>
    <read><delim>\x0a</delim><match><data>Magic number: 0x4242</data></match></read>
    <read><delim>\x0a</delim><match><data>Future: 0x7072</data></match></read>
    <read><delim>\x0a</delim><match><data>Offset: 0x8</data></match></read>
    <read><delim>\x0a</delim><match><data>Title: vehicles</data></match></read>
    <read><delim>\x0a</delim><match><data>Entry Count: 0x3</data></match></read>
    <read><delim>\x0a</delim><match><data>make: cbababcbacbcbaaca</data></match></read>
    <read><delim>\x0a</delim><match><data>model: baccccbcbbabaaa</data></match></read>
    <read><delim>\x0a</delim><match><data>doors: 0x7a</data></match></read>
    <read><delim>\x0a</delim><match><data>Title: books</data></match></read>
    <read><delim>\x0a</delim><match><data>Entry Count: 0x4</data></match></read>
    <read><delim>\x0a</delim><match><data>author: bcbcaaaaaa</data></match></read>
    <read><delim>\x0a</delim><match><data>made into a movie: true</data></match></read>
    <read><delim>\x0a</delim><match><data>summary: abaacabbababaacc</data></match></read>
    <read><delim>\x0a</delim><match><data>publisher: cccaaabbaccabbabaccaaacb</data></match></read>
    <read><delim>\x0a</delim><match><data>Title: movies</data></match></read>
    <read><delim>\x0a</delim><match><data>Entry Count: 0x3</data></match></read>
    <read><delim>\x0a</delim><match><data>title: accaacbaacbcca</data></match></read>
    <read><delim>\x0a</delim><match><data>plot summary: abbcaaaccbaac</data></match></read>
    <read><delim>\x0a</delim><match><data>year released: 0x93fa</data></match></read>
    <read><delim>\x0a</delim><match><data>Title: vehicles</data></match></read>
    <read><delim>\x0a</delim><match><data>Entry Count: 0x4</data></match></read>
    <read><delim>\x0a</delim><match><data>WRONG FORMAT: 1 vs 3</data></match></read>
</replay>
</pov>

=== funemy/binary-study/cqe-challenges/NRFIN_00026/pov/POV_00116.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE pov SYSTEM "/usr/share/cgc-docs/replay.dtd">
<pov>
<cbid>service</cbid>
<replay>
    <write><data>\x04\x04\x00\x00</data></write>
    <write><data>\x01\x00\x00\x00\x01\x00\x00\x00\xf0\x03\x00\x00\xe8\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe8\x03\x00\x00\x3du\x8b\x94e\xbb\x8c0jQ\x85\xba\x8e\x00\x00\x00p\x14\xfc\xdb\xd6\xa8p\x10\xbf\x09\xd9\x1e\xac\x0e\xea\x0d\x1dq\x5b\x60\x85\xf3\xdaS\xbf\xb6CG\x60\x60\x0d\xec\xe5\x24Q\x22\xcc\x1di\xcfy\xea\x92\x1dC\x1fs\xc2\x2bZ\x3e\x0a\xd2V\xc9\x07\xf3\xdd\x038\x9ci\xae\x079\x2b\xa1\xdbq.e\xa9EsNL\xd1\x10\x0e\xc1\x84\x40\x06a\x80f\xe1\xf1\x96\x27\x92\x9aq\x9a\x27\xa8\xd0M\xa4\xcb\x9b2\x29\xfa0Tx\xc6z\xcc\x02\x80?QG\x12\x19\xff\x3d\x9c\x00x\x83c\x87\xf6\xec\x40\xee\xbd\x97\xf6u\xfc\xaa\x99\xf6\xf1\xc4\xf1y\xb2\x5f\xe32\xc00d\x5df3f\xc2\x08\xfc\xf1j\xf6\x81\x90\x16r\xc1\xc3p\x06L\xa0Q\x19\xfc0\x06\x03\xed\xc9\x5cDZ..\x9e\x9dJ\xa6\x93\x04\x05\x80K\x15RIuV\xc5\xdb\x02\xe5\x23\x9b\x2f\xde\x09\xcb\xc1\x7d\xe8\xd5\xef\xb6\xf4\x04\x94S\xe3q\xc0\x95\x0e\xe8:tl\xc5h\x5e\x18\xdf\xa2\xdd\xe4n\x5fa\xf3\x96\xad8\xc3U\xda\xdf\x8bF\xee\x9b\xc0\xdbO\xb9\x9f\x18H\x3c\x84\xac:\xcb\xf2\x18\x94\x17e\x24\xb2\xcfU\xeajo\xc7\xdf\x16QC\x5djL\x94\xda\xb3\x7dh\x80\xad\x29\xab\xf9\x18\xa6\xef\xb1x\xcfg\xbc\xd2\x0c5\xe0\xb7\xd9\xf7\x00v\xda\x26\x0d\xaa\xb5\xdf\xda\xf8\x00\x928\x60\x60\x93o\xa1H\x5e2g \x03q\x09\xc9\x22\x98\xb1\xe7Fl\x9d\xf8\x92\x28\xfeE\xb6\x26O\x60\xf28\xbak\xc8\x1c\xac\x17l\xec\xc7\x7c\x60\x00\x11\xfb\x2bW\xdf\x90\x9e\xab\x94\xa0\x1a\xac\xc0\xba!\x7d\xae\xe6C\x18S\xf9\xa2z\xea\x3b\x13n\x60\x60\x00\xe5\x8e\xebt\xa2Av\x2a\xea\xc9\xcfm\x9eo\x84!\x81\x97\x85i\xce\x3bv\x82\x0c\xf1\xffCf\xc4t\x02\xf4.K\xfb92\xbd\xa6\x1e\x3b\xe5\x0eW\xee\x02\x8bAqm\xd2o\xf7\x0f\xae\x27\xd2H\x9a\xc5\x13\xc9L\xfc\x0a6\xd2\x15\x1dg\x05\xa9B\xc0\x10h\x2f7\xf0\xfeg\x19\xfa\x83\xa5\x94\x87\xfa\xf1\x9be\xf1as\x05\x2cqHs\xfcv\xf1\xf6cm\xc34\xb0\xf8\xc3\x8d\xd3h\x12s\xa6\x92:\xefP\xb8\x9f\xde0\xeb\x5f\x24\xdd\x08AV\xe9\xbc\x25\xef\xf8\x1a8x\x94\xdb\xccn\x10\x09\xc9\x13\x5c\x8d4\xeb\x5f\xc5\x839\xea\xc5\xe31\xe2\xe7\xb6\xb0\x13Q\xe6\xed\xf6\x97\x80\x60\x00                                                                                                                                                                                                                                                                                                                                                                                                                                   </data></write>
    <read><delim>\x0a</delim><match><data>Starting dissection...</data></match></read>
    <read><delim>\x3d\x3d\x3d\x3d\x0a</delim><match><pcre>.*New Packet</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===lol</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===prelanguagecloudage</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*Dissection finished</pcre></match></read>
</replay>
</pov>

=== funemy/binary-study/cqe-challenges/NRFIN_00023/pov/POV_00003.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE pov SYSTEM "/usr/share/cgc-docs/replay.dtd">
<pov>
    <!-- Use after free -->
    <cbid>NRFIN_00023</cbid>
    <replay>
        <!-- reliability -->
        <delay>100</delay>

        <!-- Create valid order for AAAA -->
        <write><data>\x02\x00\x00\x00\x41\x41\x41\x41\x00\x00\x00\x00\x41\x41\x41\x41\x42\x42\x42\x42</data></write>
        <read><length>4</length><match><data>\xa4\xff\xff\xb7</data></match></read>

        <!-- Create valid order for BBBB -->
        <write><data>\x02\x00\x00\x00\x42\x42\x42\x42\x00\x00\x00\x00\x41\x41\x41\x41\x42\x42\x42\x42</data></write>
        <read><length>4</length><match><data>\x4c\xff\xff\xb7</data></match></read>

        <!-- Create complementary order for AAAA -->
        <write><data>\x02\x00\x00\x00\x41\x41\x41\x41\x01\x00\x00\x00\x41\x41\x41\x41\x42\x42\x42\x42</data></write>
        <read><length>4</length><match><data>\x00\x00\x00\x00</data></match></read>

        <!-- Create another order for BBBB -->
        <write><data>\x02\x00\x00\x00\x42\x42\x42\x42\x00\x00\x00\x00\x41\x41\x41\x41\x42\x42\x42\x42</data></write>
        <read><length>4</length><match><data>\xd0\xff\xff\xb7</data></match></read>

        <!-- Create complementary order for BBBB -->
        <write><data>\x02\x00\x00\x00\x42\x42\x42\x42\x01\x00\x00\x00\x41\x41\x41\x41\x42\x42\x42\x42</data></write>
        <read><length>4</length><match><data>\x00\x00\x00\x00</data></match></read>

        <!-- List stocks, triggering bug -->
        <write><data>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00</data></write>

        <!-- Terminate if patched -->
        <write><data>\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00</data></write>
    </replay>
</pov>

=== funemy/binary-study/cqe-challenges/NRFIN_00026/pov/POV_00021.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE pov SYSTEM "/usr/share/cgc-docs/replay.dtd">
<pov>
<cbid>service</cbid>
<replay>
    <write><data>\x04\x04\x00\x00</data></write>
    <write><data>\x01\x00\x00\x00\x00\x00\x00\x00\xf0\x03\x00\x00\xe8\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe8\x03\x00\x00\x27\x0d\xd4\x00g\xfc\x3edN\x2f\xe6\xda.\xa3\x1fhna3\x09s\x00\x00\x00F\x00K\xd3\x84\x85\x93\xc4.\xbcZ\x8f\x830\xebT\xde\x0b\x96\x27\xb5\x0e\x1f\x91\xbc\xf7z\x0bP\x91!\xe7\x0e\xd4\xe2\xa5\x83\x28\x9b\xdb?\xb6\xd8\x25\x24\x3d\x5b\xadw\xf4\xab4\xf2\x8bfxWe\xbb\xf7\x00u\xc4\x87B\xa5\x3d\xb8\x9bj\x00\xfe\x99\xe1\x1a\x8d\xb9\x80I\xf7 \xb8\xad\x14L\xdaIVoL\xda\xabI\xc4j\xb96\x89\xf0r\xee1\x18F\xf1\x87\xd4P\x97:f\x89\x04\xb1\xe0\xaa\x2c\xe8\xc3\xa8Y\xac\xc3F\xd0\x13\xa3\x90\x84\xff\x1b\x2d\xfb\x9db\x01\xb3\x14e\x19\xe6\xcf\x22TF\x00\x80\x98xX\xaeu\x10Z\xa2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </data></write>
    <read><delim>\x0a</delim><match><data>Starting dissection...</data></match></read>
    <read><delim>\x3d\x3d\x3d\x3d\x0a</delim><match><pcre>.*New Packet</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===rofl</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===vernileDasya</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===hookahsupersimplicity</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*Dissection finished</pcre></match></read>
</replay>
</pov>

=== funemy/binary-study/cqe-challenges/KPRCA_00016/pov/POV_00001.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE pov SYSTEM "/usr/share/cgc-docs/replay.dtd">
<pov>
<cbid>service</cbid>
<replay>
    <write><data>r\x0aZ\x0aR\x0aR\x0aSRPR\x05\x0aR\x0aV\x0aS\xf4\xe4\x0aR\x8a\x0al\x0aZ\x0aR\x0aV\x0aS\xe3k\x0aR\x0a8\x0a\x19\x0aS\xf4d\x0aZDR\x0aV\x0aS\xf4k\x0aZ\x0a8\x0a</data></write>
    <read><length>1</length></read>
    <read><length>1</length></read>
</replay>
</pov>
