=== funemy/binary-study/cgc-release-documentation/replay.dtd
<!ELEMENT pov (cbid, seed?, replay)>
<!ELEMENT cbid (#PCDATA)>
<!ELEMENT seed (#PCDATA)>  <!-- 96 hex digits -->

<!-- 
   replay specifies the sequence of actions to carry out
-->
<!ELEMENT replay (decl | write | read | delay)+>

<!ELEMENT decl (var,value)>
<!ELEMENT value (data | var | substr)+>
<!ELEMENT substr (var, begin?, end?)>  <!-- missing begin implies 0, missing end implies len(var) -->
<!ELEMENT begin (#PCDATA)>
<!ELEMENT end (#PCDATA)>

<!ELEMENT length (#PCDATA)>

<!-- timeout values are in milliseconds -->
<!ELEMENT timeout (#PCDATA)>

<!--
  allow 1 or more data elements in write to make it 
  easier for humans to hand craft mixed ascii/hex data blocks
  all data elements are concatenated and written in a single 
  operation
-->
<!ELEMENT write (data | var)+>

<!ELEMENT read ((length | delim),match?,assign?,timeout?)>
<!ELEMENT delay (#PCDATA)>
<!-- match could be a regex for example -->
<!ELEMENT match (data | var | pcre)+>
<!ELEMENT delim (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT assign (var,(slice | pcre))>
<!ELEMENT var (#PCDATA)>
<!ELEMENT pcre (#PCDATA)>

<!ELEMENT slice EMPTY>
<!ATTLIST slice begin CDATA "0">
<!ATTLIST slice end CDATA #IMPLIED>

<!--
   The echo attribute is intended as a debugging feature. When
   echo="yes", the replay utility should echo any data returned
   from a read operation to the local (replay) console
-->
<!ATTLIST read echo (yes|no|ascii) "no">
<!ATTLIST write echo (yes|no|ascii) "no">

<!ATTLIST delim format (asciic|hex) "asciic">
<!ATTLIST value format (asciic|hex) "asciic">
<!ATTLIST data format (asciic|hex) "asciic">
<!ATTLIST match invert (false|true) "false">
<!ATTLIST pcre group CDATA "0">

<!-- make whitspace matter in some elements -->
<!ATTLIST data xml:space (preserve) #FIXED "preserve">
<!ATTLIST delim xml:space (preserve) #FIXED "preserve">
<!ATTLIST pcre xml:space (preserve) #FIXED "preserve">

=== funemy/binary-study/cqe-challenges/KPRCA_00033/pov/POV_00000.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE pov SYSTEM "/usr/share/cgc-docs/replay.dtd">
<pov>
<cbid>service</cbid>
<replay>
    <write><data format="hex">120000000000000048454c4f6701c800000058cedd263c000000000000004b45595800100000004e494345204b4559204953204e494345444154414443424106000000594f594f594f4b4559580000000000d7d657231a00000000000000444154410100000006000000594f594f594f19a37ce204000000010000000400000002000000</data></write>
    <read><length>82</length><match><data format="hex">5155455545440a5155455545440a5155455545440a48454c4f205b56455253494f4e203130335d205b534543555245206f6e5d205b54544c203230305d0a4e4f204b45590a50524f4345535320444f4e450a</data></match></read>
</replay>
</pov>

=== funemy/binary-study/cqe-challenges/NRFIN_00026/pov/POV_00047.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE pov SYSTEM "/usr/share/cgc-docs/replay.dtd">
<pov>
<cbid>service</cbid>
<replay>
    <write><data>\x04\x04\x00\x00</data></write>
    <write><data>\x01\x00\x00\x00\x00\x00\x00\x00\xf0\x03\x00\x00\xe8\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe8\x03\x00\x00\x1b\xe1\xed\xb8!R1\x29p\x3e\xf7\xfb\x8a\xf9m\xf4\xb0\xf3tZ\x08\x01\x00\x00\x26\xda\xd8\xffO\xe9\x86!\xb4i\xae\x24\xc3b\x03\xd2\x1d\x60\x29m\x0d\x29\x99\xe5\x81\x2f\xb1\x93\xb8\x8eE\xbbS\x8af\x8e\xc3t\x00\x05\x8dqr\xd59\xb1\xa3n\xef6\xe0\xd0\x7f\x172\x0e\xe2nz\x82\xb5\xc6\xf5kq\x90c\xcfG\xca\xf7J\x0d\xf2\xf5i \x05Z\x09\xe1\x86\x2c\xcbe\x2d\xd4\xfa\x2f\x7e\x1f\xa5\x0f\x92\xb8\xd3blD\xf3\x00\x0d\xd6\x95\xf0b7\xd1\xd1R\xee\x7b\xf8\xc8\x19\x97z\x2d\xb8\xb9QmB\x22\x07\xc4Y\xaa\xb6\x0c\x1a\xf5N\x94\xca\x8e\xa0\xe2\x28\x88\x5e\xa7\xcdIR\xd4\xdd\x1cn3\xc8\x40\x94Da\xb4\x7d\x2dZ\xa2\x0a\x017\xb2\x1f\xba\xd1\xa8\x86s\x8d\xfc\xd9h3\x1cI\xbf\x03o\x5b5\x91S9\x2d\x3e\xff\xbc\xbe\xb9cm\x86\xc0\xc6\xf8\x8fO\xbbN\x0eX\xb4\x7c\x03\xca\xabj\x40\x95\x25p\xb0\x96\x05\x2c\x1aXG\x29\x168\xed\x80\xdc\x23s\x2akJsOjM\x27T\x8b\x40\xc0\x0f\xc8\x1b\xf6\x9b\x7d\xc9\x26\xd1\xab\x95H\xba\xb6\x01\xb5\xe3\xe4\x9ajC\xb7T5\x2c\xc8\xa6\x8e\x9bC\xba\xb2\xb8\x92D\xd1.\x90\x5b\x5f\xd3\x27\x00\x85\x84\xf0\xb8\x85\xc6 \x0d\x04\xf6\x5f0\xfd\x04\xec\x17\xaaq\xad\xd0\x0bL\xbd3f\xf7\xab\xa5x0\xd6\x24\x5bv\xe3\xc4\x07\x04\xfe\x03p\xeaV\x26V\x85d\x24Nb\xea\xf6\xd9\xd4\x8fK\x84x\xe2Z\xc5\x8ef\x16\x00\xfdc\x83BS\xc3\x27\x19\x2c\x3d?a\xec9\x2faA\x8c\xd4\xef\x5f\xc6k7\xb5\xd0\x08\x80\xc4\xe3ZF\x5dX\x1f\xf4\xad\xad\xferv\xd8\x26\xe03C\xfb\xc0\x5f\xc8\xd0\x92\x19\xcd\x9a\xb2\xd7M\x5bS\x8f\x24\x94\x95\x09\x5c\x25X\x2f\x8d\xe3\xeb\xc2vz\x09\x26\xe1\xb0k\xc6\x1aj\x8b\xe42\xc0\x5c\x7d\xb2S\xa8h 7\xfa\x87\x96\xfb\xe2d\xf2\x5f\x96W\xdc\x0dh2\xdbj\xe76Xv4\x19\xb8\x3d\x23\xeaN\x98\x7dK\xff\x1e\xf3\x011\x5bd\xe9\xa0\x5e\xce\x94b\x1e\xc6\xc8\x9a\xff\x27\xe3\x81\xa6\x24s\x5c\xea\xd3RaFm4\x94\xc5m\xc1\xe4\x7cx\xf9\xf0\xe5\xb77bx\x1d8i\x1dN\x2c\x7dn\x91\xdb\x3e\xae\xe4\x7c\xee\xcc\xb5\x87\x9a\xa8I\xf3\x06\xf9\x92\x08\x9bmOhj\x00\xa1E\xfa\x1f\xc8\xa7\xf1C\xf0\x60\x8d\x07\x07\xd8\xbf\xc3\x97\xf5\xc8\xf7XF\x2d\x89Ak\x0a\x9e\xa0\x18\xed\x05\xe6\xb6rber                                                                                                                                                                                                                                                                                                                                                                                                   </data></write>
    <read><delim>\x0a</delim><match><data>Starting dissection...</data></match></read>
    <read><delim>\x3d\x3d\x3d\x3d\x0a</delim><match><pcre>.*New Packet</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===rofl</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===nontechnicalrongeur</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*Dissection finished</pcre></match></read>
</replay>
</pov>

=== funemy/binary-study/cqe-challenges/NRFIN_00026/pov/POV_00129.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE pov SYSTEM "/usr/share/cgc-docs/replay.dtd">
<pov>
<cbid>service</cbid>
<replay>
    <write><data>\x04\x04\x00\x00</data></write>
    <write><data>\x01\x00\x00\x00\x01\x00\x00\x00\xf0\x03\x00\x00\xe8\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe8\x03\x00\x00\xd7\xdb\x3d\xe8\x92\xf4\xd9d\xb5P\xf5\xef\xe1\x00\x00\x00\x3e!\xf7\x0c\x0e\xa6u\xc0\x9f\xb4\xc0Y\xd6M\x07\x17Pd\xbf\xd8\x7e\x60c\xb5\xe4\xd6Tw\x105F\x00\xcd\x9a\xd4\x82\x3b\xad\x17O\xaf\x19x\xc0B\xb5\x7fK\x16\x90\xabv\xd8\xf6\x3d\xe0u\x3cg\xddD\xad\xca\xf8\x97\xee\x88\xa1\x2a\xa6\xce3\x94\xa93c\x7c\xe6\x14\xb6\x5fa\xcdm\x5dY\xae\xa8D\xec\x3c\xe3\x12\xf2\xd6\x7d\x3dM\xf2\xc2\x24:\xeaTls\xaf\xc1\xd7Q\x29\xd9\xb4\x99\xda\x98jW\x5b8\x8eB\x12x\x93\xbc\x19T\x88\x0b3\x7f\xf5m\xb3\xc7\xd8\xca\x97\x86\xde\x0d\x0a\xfd\x18\xe2\xd2fE\xd8W3\xac\xe8\xca\xc9\xf16\xab\xb8 y\x2bJ\x9d\x5b\xee\x3b\x90\x9aO\x3b\xc1\xaf\x00\x8e\xf2\x8cb\x1d\x40\xf64\xbf\x2a\xfb\x5c\xb7.\x8a\xc3\x84\xef\x9f\x1cC\xe8c\xda\x9dFf\x84kA\x9e\xcb\x2d.\x14g\x2fr\xee\xbe\xbbw\xad\x2dP\x84\xe0\xb7\x2c\xa9\x16\x7b\xbf\x13\x8f\xfe\xb3\x3b\x7d\xec\xb7\xee\x1a\xe6\x29L\xe3\xc0\xbc\x9b\x0ay\xbbN\x3e\xb4\x0e\xaa\x26\xc2\x8c\x2d\x7en\xd1\x1b\xa9\x11\x5e\x8b\x26\x9f\xc2\x1d\x1f\x9dn\x0f\x11\x00\xc5\x06uUXR\x976\xb5k\x82\x00\xf5\xe8\xcb\x10\x17\x00\x17\x18t\xfa\xdf\x96\x2fh\x98\xa8\x87\x03\x07p\x90\x13\x81\x0f\x0d\xfb\x9b\x17\xe6LY\x95IIG\x5c\x96\x96\xda\xf0oXL\x0dF\x80j\xf3\xe5\xc68c\x5f\x03 \x0a\xb5n\xb3\x3ei\x18\x8f\xa7\xdeox\xae\xa6o\x7b\xd1\xdf\x8bNn\x92\xd6\x8ag5\x09\x92\x8d\x9b\x9c\xb9\x9c\x1a\x969\xcb\x0d\x842\x3dp\xb6\x22:K\xb6\xcf6YO\x7c\xd8\x91\xccAw\xfd\x3d\x912\xd2\xd2\xbb\xb6l\x3c\x8c\xbbr\xa4\x81\xe6Ne\x02\x96I\xc0\xb2\xc1\xb8\xbe\xd1\x86\x5d\x22\x29Q\x01\xf6l\xa6\xc2\xf7\x08\x89\x09z\x26\x17\xad\x3e\x7f\x12\xef\xfb\xe4r\x23\xf2\xf6\xa0\x7c\x03\xf3d\xbd\xed\x28\x05\x08i\xad\x1a\x88f\xe4\x23\x17\xcb\xca\x8c\x03\xf6t\xae\xb2\xc9c\xfb\x94\x27\xf8\xba\xab5Y\x16\xbb\x1e\xe0\xafo\x22\xab\x1aLC\x9c\xa4l\x175qq\xef\xa8\x2c\xf3i\x86\xa3S\xac\xd6\x5f\xb6\xebuH?\x25\xfee\xb4W\xac\x03\xa4\x03\x0f\xf8\xa6\xd2\xff\x1cx\xa02\xb1\xd8\xa5\xa1\xc0\xb1u\x7c\x85\x01\x88\x13\x9a\xb8\x1e\xf29\x1f\x26R\x11o\xc1t\xe2\xc0a\x1e\xba\x93\xbe\x22\xcfO\x5f!\xe3\x7ct\xa5\xd1.\x10\x8d\xdd\xff\xb4\x23C\xd3\x1e\x8c\xa2\x07\x3d\x89\x7d\xc9\x2a\xe6n\xe5\x18\x07\xe9\xcd\x92W\x87\x02\xab\x86H\xe0\xbe\x1c\x94N\xbd\xf4M\x94\xbd\xa3:\xbfnD\x11\xb2\xdfY\xb9\x1d9\xc4l\xeaO\xa2\x9b\x5d\x90a\xb0u\x5f\xcd\xf0\x2a\xfe\xe3f\xcc\x3c\x815\x1f\x85\xdc6\xe8!\xba\x92\xc2\x80\xf2\xef\xfb\x81\x17\xbc\x7c\x0c.\x2c\x7d.9\x08\x9a\x81\x8b\x10\xe3k\x3b\x28\x81\x92\xb6\x3bT\x24\x16\x60\xb5\x5c\x0e\xe4\x8b\x1f\xd4\xea\xa1\x05\xe0\x17\x17\x00M\xbb\xf3\xe3\xee\x2c\x93\x83TJ\xcd\xe4\x17\x17\x00\x80\x90\xe9\xc7K2L\x11\xfc\xe4\xd4\x96\xf9 zRZC\xb7\x5c\xeeq\xfd.\xe1r\xf2\xa4\x1aZm\x1b\x8c\xee\x90\xb7\xach\x07\xa1\xfb\xe9\x08\xd2\xbaz\x18\xf1B\xd6\x7e\x26\x9e\x03e\xfeZ\x1f\x84\x16\xe1\xeeW\x11\x04\x838\x12\x5c\xf7f\x2d\xb1\xdb\x2f\xdbDv\xec\xa5\x19L\xb2T\x26.\x805\x2co2\xde!\xef\x89\xecz\xdc\x7dC\x95\x7c\xf0\x5cT\xe1l\xe2\x93a\x03\xb6\xa2\x27h\xcc\xael\x7e\xdf\x9fi\x5e\xb7EM\x82r\x22u\x08\x0c\xed\x92\xea\xf0S\xe2Q\x7f\x2b2\x27M\xb2!\x80\xcb3R\x3d\x03M\xaa\xb7x\x01d\x2bw\x7c\x22F\xbf                                                                                            </data></write>
    <read><delim>\x0a</delim><match><data>Starting dissection...</data></match></read>
    <read><delim>\x3d\x3d\x3d\x3d\x0a</delim><match><pcre>.*New Packet</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===lol</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===Zantedeschiacladocarpous</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===loungyimpolite</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*Dissection finished</pcre></match></read>
</replay>
</pov>

=== funemy/binary-study/cqe-challenges/NRFIN_00026/pov/POV_00167.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE pov SYSTEM "/usr/share/cgc-docs/replay.dtd">
<pov>
<cbid>service</cbid>
<replay>
    <write><data>\x04\x04\x00\x00</data></write>
    <write><data>\x01\x00\x00\x00\x01\x00\x00\x00\xf0\x03\x00\x00\xe8\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe8\x03\x00\x00\x16\xd7\x5b\x5dH\x00\xea\xf9\xb7\x25\x8f\xa4\xab\x01\x00\x00\x88\x2a\x9a\xa1\x40\x00a8\xe7g\x40\x00\x40\x40\x00n\x80\x3b\xfa\xcb\x97\xea\xe6a\xb9r\x93\xbe\x7d\x22\xba\x40E\x01\xef\xbd\x3c\xa6\x90\x1d\xa8\x8a\x7eUk\xddUI\x5czF\xeaW\x80\x28I\xa2\xfb5\xc3\x03\xd9V\x9f\x88\xa1\xe8\x02\x7b\xdca\xbe\xca\xf5\x8b\x92GEN\x298\x9a\x02A\xe0\x28\xf7\xfc\x98\x85\xf8\xd6\x22\xae\x22\xb5\xce\x1dl\xa8\x1f\xf6G\xf9\xff\x8e\xec\x14\x9a\x29\xa1N\x3b\xf2\xb6v\xf8\x0c\xe8QP\x85j\x60\x24\xc5\x3d\x8c\x23\xc8\xb6\xd4t\x09G\x1d\xf6F\x0b\x29\xf4\x97A54\xbd\xb72\x1d\xcb4\x08\xbc\x1f\xb9\x1c\xfe\xf8XK\x88\x3e\x2f\x8eI\x80\xf5\x7bp\xecC\xa2\x80\x25E\xe2\x0a\x17\xef\x10\x87\x94\xd7\xa12\xfd\x2f\xbf\xd7\xb2ph\xf0\xe3\xa9\x9cN\x0d\x06lc\xea\x94a\xc1B\x94\xcai\xdd\x10o\x5d\x0cw\x15\x1ba\x99q\x97\xd8\xff\xfa\xde\xb8\x8b\x98\x01\x8c\xdbq\xfc8\xac\xf253\x1e\x80\x60O\x27\x8f\x10\x2b1\xde\xc1\x3b\xa3\x2a\x5d\x87C\xff\x08wEk\xf1\x09\xe8IQx\x06\xb5vs\x7c\x11\x29\x40\xc0\xbb\x0b\xab\x01\x0a\xff\x04U\xc1\xfa\x84H\x1bS\xf5\xee\xcd\x121\x27b\xd31N\x19\x87spj\x0f\xda\x24\xbe\x1a\x60\xfc\x91Y\xc9Ib\x8a\xe6\xd4Mz\xdewS\x0bv\xd0\xb3aNHun\x18\x5c\x2b\x11\x28\x02\x40\x00\x40\x40\x00\x7e\xd3\xee\x8f1\xe7\xee\xf1\xb8!\xca\x9b\x7d\xa5\xd1\xc4O\x07\xabk\xeb\xe3\x8e\xa0\x19:ytD\x1d\x94\xc1\x95\x2ca \xa6H\x5cNI\xa2s\x92\x92\xbc:\xca\x94\x91\x9bw\x85\x28\x8c\xe9\x87\xf9\x08\x89\xc9\xf6\x7dw\x2f\xe1\x24\xd9\xaa\x15Z\x9b\xb9\x96X\xc2\xa0\x17\x05y!O\xed\xb1\x10\x40H\xec\x80\x11\x0f\xe6\xcc\x8d\xd0X\xe3\x92\x19\xc3\x3dc\xd5\xf9m\xb5a\xef\x27\xf2\xb6\xee\x93p\x7fG\x8c\xbb\xe8\xba\x9a\xc22\xaelBN\x25\x0aW\x2aJ\xa5\xc9o \xa8n\xd8\x0e\x7d\xc0T\x071\x27\xeb\x27g\xf4c\xd4\x9c\x2f\xc9\x185\x5bA \xd2\x2c8\xa85\xa1\x93Q\xac5:\x84\x98S\x01\x15\xc3\x9b\x90\xe5\xe4\xd0YW6W\xbf\x18:\xc6\xe3\xbb\xd4\x83\xaaA\xf6\xb4i\x5e\x0f\x9d\xaeS\xbc\xd1\xae\x12\x0b\x14\xb5\x852a\x84\xb2\x7d\xd3\x2c\x86it\x24\xbc\x40\x00\xfe\x90\x5d\xb2\x27\x8a\xd3\xca\xc4\xf0\xd5w\x40iR\xd9\xb1R\xaap\x89r\xae\xf1\x5eV\xfb\xe6q\xc9\x3b\x0d\x89\xdd\x17\x5f.p\xc3i\x98\x96\xc7\x7czo\xa2DZc\xd6\x99\x0bk\xe2\xa7!\xfc\x3cf\x9e\x83\x98\xc2\xa7\xeb\xe3W\xf9\xe9\xe2\x5c\xca\xf4\x1a\xdd\x1e\xcf\xd2\x98\xd3\xbf\x5dGjPy\x29z\x89\x89v\xac\xb2\x90lz\x00\xa8\xc4\xa13\x0ay\x16\x05\xd2\x84\x9c\x5e\xe2g                                                                                                                                                                                                                                                                                                              </data></write>
    <read><delim>\x0a</delim><match><data>Starting dissection...</data></match></read>
    <read><delim>\x3d\x3d\x3d\x3d\x0a</delim><match><pcre>.*New Packet</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===lol</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===unexchangedsupraventricular</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*Dissection finished</pcre></match></read>
</replay>
</pov>

=== funemy/binary-study/cqe-challenges/NRFIN_00026/pov/POV_00017.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE pov SYSTEM "/usr/share/cgc-docs/replay.dtd">
<pov>
<cbid>service</cbid>
<replay>
    <write><data>\x04\x04\x00\x00</data></write>
    <write><data>\x01\x00\x00\x00\x00\x00\x00\x00\xf0\x03\x00\x00\xe8\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe8\x03\x00\x00\xb3\xcf\xb3\x0c\x2d9\x04\xe6J\xc0\xab\xce\x8d\x9c\x7do\xc2\x15zZf\x00\x00\x00\xdb\x1b\x0e\xfby\xc0i7\xdb\xc6A\xef\xf3\xb8ng\x0dTE\xc32\x91\x07\x8ey6i\xef\xe0\x0a\xee\x05\x97\xf4HA\x8c\x60\x86\xac\x02\x9a\xf4\x3cc\xe0Y9uV\xd2\x05\x40\x5f\x85\x00\xf8\x7d\x7f\x2f\xfc\x84\xfa\x5c\x159\xfa8\xdeg\x15p\x40O\xc8\x1e\xe3u\xb8\x9a\x2b\x09\xb31I\x9d\xea\xac.8b\xb4\xbd\xadj\xb4I\xc2\x16y\x28\x9f\x23\x12\x07\x2c\xa8eC\xda\x93\xfc9C\x23\x3cf\xaf\xd5\x97\x97\xebS\xbc\x1a\xfa\x91\x87\xac\xeb\x10\x0c\xd2hv\x1d\xect\x5f\x7e\xaa\xcd\x88\xc8\x18\x7b\x9e\x1a\x902\xd2\x84\xf2F\xec\xbc\xe6\x15\x0d\x0c\xd6l\x87KzU\xa8\xfa\xf6\x2b\x04\x12\x0d\xb6\xdb\x0e\x9c\xcb\x00R\xe0:\xe9\xd0\xdbj\xd0\x17fiS\xb0\x2b\x2c3\x9f\x0b\x2b\x07\xa7\x28\x9e\x04Zej\x5f\xf4f\x91\xac\xf9\xc7\xa0\xbb\xc3\x970\x8c\x5c\xc4\x3b\xdfS\x5f\xf6\x7d\xe6\xc3\x8d\x01:\x06F\xa3e\x7f\xac\xb0\xc2\x9eT\x26\x00\xa1\x08\x26\x10l\x8d\x7bkA\x7c\xefL\x0a\x5d\x04\x19s\x5e\x858\x9a\xe2\xcc\x3e\xfb6\x8d\x08e\xa2\x5d\xe5\xa9\x8f\x84K\xfd\x00E\xc5\x0b\x1e\xb1\xaa\xc8\xf1\xe6\xdeH\xea.rIP\x9eW\xb4\xb1:\xba\x90\x931\xee\x9f\x7d\x9c\x22\xdc\xf0\x1da\x8f\x04\x1b?w\x7e\xe0\x85\x5e?\xd7\xee\x85\xb0\x95\xfcq.\x1fYT\x84DB\x2c7\xe4\xd4\x3b\x14\x5ca\x1c\xfb\x40\x25v\x8eC\x02\xa8\x992\xe5\x15\xfaV\xb2\xf4N\x27\xa8\x8fk\xd0\xd0\xc1\xb8\xce\xe4\xd5\x0c\xdaPR\xafx\xf0\xbc\x18sr\x01.\xb3\xac\xe0\x8au\xf7\xda\x02\x26hB\x10\x7b\xbf\xc9K\xbe0\xb8\x2cH\xcc!\xf7\xb5\xa42\x23\xfd\x8a\xb9\xcd?z\x2d\x1c\x13\xa3r\x16\xa5M0\x8a\xbcC\x07\xce\xdf\x11\xafK\xec4\xdaMU\xcf\xa1y\xbb\x8fs\xaf\xd3M\x98\x29S\x08\x9d\xa6\x2a\x03k\x8dN3\xed\xcb\x60q\xf4\xd7\x87\xcd\xb4\xb9\x29\xccJoA\xa6\xc7\x24\x3dpK\xe6\x3c2\xdf\x13\xc7\xdb\x9c\x9d.\xfa\xb4U\x2f\x2b\x26\xeaZ\x92\xa5\x22\xec\xc1\xa7w\x8e\xc0\x00\xcd\x91\xe3\xc2\xfb2\x5f\xafz\xfe\x89\x95\xf1M\xe1\x1a\x1f\x0b\xb9\xa1\xb1!J\xc2wm\xea\xa0P\xd0\xeex\x82\xe4:\x7d\x3b\xd7c\xc6o\x9eo\xd0J\xc6X\xad\x93\xdc\xff\x12\x16\xd4\xa6\x7e\xe8C\x2d\x875\x07\xde\x3eMw\xbf0\xa4\xeb\x10\x0e\xb0\xec:\x82\xe2\xa2\xe2b\x17\xca\x7b\xeb\x96\xb9\xeb\x08\xd5\xda\x95\xed\xcf\xec\xa2G\x7b\x7d.\xda\xfa\xd9Ix\xe4\x2a\x1d\x29\x1d\xa2a\xaa\xc1\x91L\xcb\x16:\x2a\x9d\xf7:\xa9\xd8\xf6\xc1rA\xd9\xd2bg\xa9yQsN\xeb \x08\xa87\xc8\x5e\xc4\xc3\x03\x00s\x89\xfd\x04\x5e\xdc\xec\x3bb.\x7f\x25\xcf\x3b\x04C\x24\x83\xcb\x1d\x0dMO\xd4\x7c\x5f\xdf\x02\x3eu\x98\x8b\x22\xcc\xa0\xba\xaaK\x84?\x7eXu\x09\x07\x9cRv\xdc\xf3Ef\xf3\x8cQ\xfe\x7dE\xb5i\xf2\x0b\xc7\xa6\xf0\xa1\xf0\xab\x28M7\x02\x23\x0d\xbd\x5f\xf1\xddE\x03\x960\x9bL\xa9\x60\xd4J\xda0\x5c!.\xc6\x7e7\x9c\x94\xe6\x0f\x5b\xe8D\x83\x22\xf8\xf8\x06\x83\x85\xdcs\xaf\xe4\xea\x94\x7d\xde\x29\x7fx\xa6\xd1\xb8\x87\xd1\x17\x16\x03\xb2\x88\xa6\xc4\x7d\xfc\x40m\xb1\x9b\xb764\x87H\xe2\x2f\xb2I\x29\x04\x29\x3b4\x0f\x22\x5c\xae.G\x91\xec\xc3M\xb5\x83\x98\x88\x93L\x2br\x99\xbaUV\x9b\xb7\x80E5\x7dU\x27rpn\x90\xfb\x05\x95\x09\xf2\x8b\xf1\x81\xe7OFjv\x84\x0fC:l\xe32\x96\xf7q\xde\x82s\x04\xfeR\x951\x07\xdc\xc8\x90\x9e\xca\x7c\x8e\x8de\xfd\x7d:\xc9\xc8\xd6x\xae??\x12I\xbc\xb2\xd0vzb\x0d\x9d\xde\xd2\xae\xbb\xe6\x843\x40\xf1\x2cY\xe5\x01\x7f                                                 </data></write>
    <read><delim>\x0a</delim><match><data>Starting dissection...</data></match></read>
    <read><delim>\x3d\x3d\x3d\x3d\x0a</delim><match><pcre>.*New Packet</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===rofl</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===acanthopterygianMuranese</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*===tecalipalingenesy</pcre></match></read>
    <read><delim>\x3d\x3d\x3d\x0a</delim><match><pcre>.*Dissection finished</pcre></match></read>
</replay>
</pov>

=== funemy/binary-study/cqe-challenges/NRFIN_00016/pov/POV_00004.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE pov SYSTEM "/usr/share/cgc-docs/replay.dtd">
<pov>
<cbid>service</cbid>
<replay>
    <write><data>\x16\x00\x00\x00robots only\xff\xff\xff\xff\xff\x9c\x0d\xd1i\xa5\xd2\xe63\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00j\xe9m\xc8\xd8\xf3\xe5\xa3\xa6\xaa1\xd6\x22\xe6\x84\xc2nly\xff\xff\xff\xff\xff\x13!\x85\xdd\xa6\xdav\xa8\xb5\x2cU\xfe\xfb\xd8\x2c\x06\xf3U\xa4\xf7</data></write>
    <read><delim>\x0a</delim><match><data>This is not the function you\x27re looking for.</data></match></read>
</replay>
</pov>

=== funemy/binary-study/cqe-challenges/CROMU_00040/pov/POV_00000.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE pov SYSTEM "/usr/share/cgc-docs/replay.dtd">
<pov>
<cbid>service</cbid>
<replay>
    <read echo="ascii"><delim>\x0a</delim><match><data>\x0a</data></match></read>
    <read echo="ascii"><delim>\x0a</delim><match><data>1 \x2d Enter a Recipe\x0a</data></match></read>
    <read echo="ascii"><delim>\x0a</delim><match><data>2 \x2d Find a Recipe\x0a</data></match></read>
    <read echo="ascii"><delim>\x0a</delim><match><data>3 \x2d Print Tagged Recipes\x0a</data></match></read>
    <read echo="ascii"><delim>\x0a</delim><match><data>4 \x2d Print Shopping List\x0a</data></match></read>
    <read echo="ascii"><delim>\x0a</delim><match><data>5 \x2d Exit\x0a</data></match></read>
    <write echo="ascii"><data>1\x0a</data></write>
    <read echo="ascii"><length>13</length><match><data>Enter Title: </data></match></read>
    <write echo="ascii"><data>hi\x0a</data></write>
    <read echo="ascii"><length>74</length><match><data>Enter the measurement and ingredients\x2c one per line.  A blank line ends.\x0a\x0a</data></match></read>
    <write echo="ascii"><data>apples\x0a</data></write>
    <write echo="ascii"><data>\x0a</data></write>
    <read echo="ascii"><length>60</length><match><data>Enter the step by step instructions.  A blank line to end.\x0a\x0a</data></match></read>
    <read echo="ascii"><length>8</length><match><data>Step 1: </data></match></read>
    <write echo="ascii"><data>\x0a</data></write>
    <read echo="ascii"><delim>\x0a</delim><match><data>\x0a</data></match></read>
    <read echo="ascii"><delim>\x0a</delim><match><data>1 \x2d Enter a Recipe\x0a</data></match></read>
    <read echo="ascii"><delim>\x0a</delim><match><data>2 \x2d Find a Recipe\x0a</data></match></read>
    <read echo="ascii"><delim>\x0a</delim><match><data>3 \x2d Print Tagged Recipes\x0a</data></match></read>
    <read echo="ascii"><delim>\x0a</delim><match><data>4 \x2d Print Shopping List\x0a</data></match></read>
    <read echo="ascii"><delim>\x0a</delim><match><data>5 \x2d Exit\x0a</data></match></read>
    <write echo="ascii"><data>2\x0a</data></write>
    <read echo="ascii"><length>19</length><match><data>Enter search term: </data></match></read>
    <write echo="ascii"><data>hi\x0a</data></write>
    <read echo="ascii"><delim>\x0a</delim><match><data>\x0a</data></match></read>
    <read echo="ascii"><delim>\x0a</delim><match><data>\x0a</data></match></read>
    <read echo="ascii"><length>6</length><match><data>\x09\x09hi\x0a\x0a</data></match></read>
    <read echo="ascii"><length>12</length><match><data>Ingredients\x0a</data></match></read>
    <read echo="ascii"><length>12</length><match><data>\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x0a</data></match></read>
    <read echo="ascii"><length>7</length><match><data>apples\x0a</data></match></read>
    <read echo="ascii"><delim>\x0a</delim><match><data>\x0a</data></match></read>
    <read echo="ascii"><length>13</length><match><data>Instructions\x0a</data></match></read>
    <read echo="ascii"><length>13</length><match><data>\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x0a</data></match></read>
    <read echo="ascii"><delim>\x0a</delim><match><data>\x0a</data></match></read>
    <read echo="ascii"><delim>\x0a</delim><match><data>\x0a</data></match></read>
    <read echo="ascii"><length>35</length><match><data>Would you like to tag this recipe? </data></match></read>
    <write echo="ascii"><data>y\x0a</data></write>
    <read echo="ascii"><delim>\x0a</delim><match><data>\x0a</data></match></read>
    <read echo="ascii"><delim>\x0a</delim><match><data>1 \x2d Enter a Recipe\x0a</data></match></read>
    <read echo="ascii"><delim>\x0a</delim><match><data>2 \x2d Find a Recipe\x0a</data></match></read>
    <read echo="ascii"><delim>\x0a</delim><match><data>3 \x2d Print Tagged Recipes\x0a</data></match></read>
    <read echo="ascii"><delim>\x0a</delim><match><data>4 \x2d Print Shopping List\x0a</data></match></read>
    <read echo="ascii"><delim>\x0a</delim><match><data>5 \x2d Exit\x0a</data></match></read>
    <write echo="ascii"><data>3\x0a</data></write>
    <read echo="ascii"><delim>\x0a</delim><match><data>\x0a</data></match></read>
    <read echo="ascii"><length>6</length><match><data>\x09\x09hi\x0a\x0a</data></match></read>
    <read echo="ascii"><length>12</length><match><data>Ingredients\x0a</data></match></read>
    <read echo="ascii"><length>12</length><match><data>\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x0a</data></match></read>
    <read echo="ascii"><length>7</length><match><data>apples\x0a</data></match></read>
    <read echo="ascii"><delim>\x0a</delim><match><data>\x0a</data></match></read>
    <read echo="ascii"><length>13</length><match><data>Instructions\x0a</data></match></read>
    <read echo="ascii"><length>13</length><match><data>\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x2d\x0a</data></match></read>
    <read echo="ascii"><delim>\x0a</delim><match><data>\x0a</data></match></read>
    <read echo="ascii"><delim>\x0a</delim><match><data>\x0a</data></match></read>
</replay>
</pov>

=== funemy/binary-study/cqe-challenges/NRFIN_00025/pov/POV_00000.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE pov SYSTEM "/usr/share/cgc-docs/replay.dtd">
<pov>
<cbid>service</cbid>
<replay>
    <write><data>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00</data></write>
    <read><length>256</length><match><data>\xff\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xcc</data></match></read>
    <write><data>\xad\xaa\x5b\xc5qR\x261\xf1Ot\x92\x27\x14\x7e\x95</data></write>
    <read><length>16</length><match><data>\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e\x0f</data></match></read>
    <write><data>\xf2j\x29 J\xce\xdc\x2f?z\x9e\x8a\xd6\xfc\xcb\x99\xdc\xfe\x05\x28\x0f\x19\x5c\xeb\x8e\x92\xa8\xb0\x2bxb\x17\x90\x8c\xe9E\x8c\x10\xfd\x98\xef\xb5\xa0\xd7\xd94\xe6\xa2\xfa\x88\x226\x3e\xfb\xf7a\xea\x04\x1e\xd4\x9f\x2f\x0d5\x2b\xda\xc4\xdc\xe5\x87\x1a\x60\xa5\x17\xe9\x89\x7bM\xe0\x9d\xea\x04\xea\xc8\xbeGBf\x3b\x96\xf6\xf6\xb1c\xf5\x26\x81\xa0\x27\x965\xe8\xa4\xe9z\x0a\xddQ\x0e\xf8.u\xa91\xf4\x17\x15\x1ce\x98\xebi\xe7\xc4O\x98\xc6\x60\x16W\x8f\xbc\x86\x2c\xcbQ\x98\x229\x3eO\xfb\xf3\x28\xe7\x0c\x88\xf6\xe1\xa7\x89\x3cW\xbe\x9f\xa87\x06\x81\x00\xa5\x84\xc8\x87\xef\xa5\x14\x7d\x0e\x5eMI \xf2\xe2Ix\x8d\x09r\xdc\x91\xdd\xf9DKsA\x93\x94\x9d\xb1f\x3b\xf5\xf3\x0e\xd8\x02\x89\x17\xfd8Z\x8d\x60\x9c\x02\xf7\xdde\x11\x7eQ\x12\xc3\x5f\xc0\xbf\xf7a\xf4\x9c\x96\xa9\xf5\x9f6aW\x14t\x2f\xdeT\xed\x19\x03\xf7\xa5\x5c\x80\xd5j\x29\xa8\x2amD\x86Uc\xf1k\x23\x0a</data></write>
    <read><length>112</length><match><data>\xc7\x83\x7b\x8f\x5em\x5c4\xd9\x40m\xce\x0cl\x1c\x82\xe8\xbao\xe7GlG5\xef\x60y\xa7\x0c\x0e\x1e\x82\xd6\xe7\x5f\x8234\x1dR\xd7hA\xe8\x2dEp\xbb\xd8\x9bL\xd0m7O\x7e\x91Y\x23\xbev6G\xab\xe2\x82W\xf9\x26e 1\xe52z\xccj\x5d\x5e\xdc\xd5\xa3\x29\x81:!gW\xcaAv\x85\x1fN\x1e\x97\xc8\xbb\x25\x94c\x0dG\x07\x90\x18\x60\xe6\x08\x40g\x96</data></match></read>
    <write><data>\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa</data></write>
    <read><length>42</length><match><data>\xff\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa</data></match></read>
</replay>
</pov>
